name: scout_spirit
description: The Scout Spirit app for the gamified progression system project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  amplify_flutter: ^0.1.2
  amplify_auth_cognito: ^0.1.2
  amplify_analytics_pinpoint: ^0.1.2
  amplify_storage_s3: ^0.1.2
  rxdart: ^0.26.0
  dotted_border: ^2.0.0
  provider: ^5.0.0
  flutter_unity_widget: ^4.0.1
  intl: ^0.17.0
  http: ^0.13.1
  jose: ^0.3.0
  confetti: ^0.6.0-nullsafety
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  device_info: ^2.0.0
  flutter_speed_dial: ^3.0.5
  image_crop: ^0.4.0
  uuid: 3.0.4
  fluttertoast: ^8.0.6
  hive_generator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  build_runner: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/jsons/resources/objectives/
    - assets/jsons/resources/lines.json
    - assets/imgs/
    - assets/imgs/avatar/eyes/
    - assets/imgs/avatar/mouths/
    - assets/imgs/avatar/neckerchiefs/
    - assets/imgs/avatar/pants/
    - assets/imgs/avatar/shirts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: ScoutSpiritIcons
      fonts:
        - asset: assets/fonts/ScoutSpiritIcons.ttf
    - family: Neucha
      fonts:
        - asset: assets/fonts/Neucha-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
