/// Flutter icons ScoutSpiritIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ScoutSpiritIcons
///      fonts:
///       - asset: fonts/ScoutSpiritIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ScoutSpiritIcons {
  ScoutSpiritIcons._();

  static const _kFontFam = 'ScoutSpiritIcons';
  static const String? _kFontPkg = null;

  static const IconData campfire = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fleur_de_lis = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trebol = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spirituality = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData affectivity = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData character = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData corporality = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creativity = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sociability = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spirituality_1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData affectivity_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData character_1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData corporality_1 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creativity_1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sociability_1 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
