/// Flutter icons ScoutSpiritIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ScoutSpiritIcons
///      fonts:
///       - asset: fonts/ScoutSpiritIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ScoutSpiritIcons {
  ScoutSpiritIcons._();

  static const _kFontFam = 'ScoutSpiritIcons';
  static const String _kFontPkg = null;

  static const IconData campfire = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fleur_de_lis = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trebol = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
